apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: hello-world-2
  namespace: flux-system
spec:
  approvePlan: "plan-main-070e1cad88" # first 8 digits of a commit hash is enough
  interval: 1m
  storeReadablePlan: human
  path: ./
  sourceRef:
    kind: GitRepository
    name: helloworld-2
    namespace: flux-system